import { userState } from "@atoms/user.atoms";
import { Login } from "@components";
import { SignedInUserOnly } from "@contexts";
import { Flex, Typography } from "antd";
import { Inter } from "next/font/google";
import Head from "next/head";
import { useRecoilState } from "recoil";

const inter = Inter({ subsets: ["latin"] });
const HeadComponent = () => (
  <Head>
    <title>Create Next App</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
);

const Index = () => {
  return (
    <SignedInUserOnly>
      <HeadComponent />
      <Flex vertical>
        <Typography.Title>Login</Typography.Title>
        <Login />
      </Flex>
    </SignedInUserOnly>
  );
};

export default Index;
