import { SignedInUserOnly } from "@contexts";

import {
  Button,
  Card,
  Carousel,
  Flex,
  Tabs,
  TabsProps,
  Typography,
} from "antd";
import { Inter } from "next/font/google";
import Head from "next/head";
import MenuList from "./index/components/MenuList/MenuList";
import { BannerCarousel } from "@components";

const inter = Inter({ subsets: ["latin"] });
const HeadComponent = () => (
  <Head>
    <title>Create Next App</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
);

const TabComponent = () => {
  return (
    <Flex vertical>
      <BannerCarousel />
      <MenuList />
    </Flex>
  );
};

const items: TabsProps["items"] = [
  {
    key: "1",
    label: "숙소",
    children: "Content of Tab Pane 1",
  },
  {
    key: "2",
    label: "추천",
    children: <TabComponent />,
  },
  {
    key: "3",
    label: "투어",
    children: "Content of Tab Pane 3",
  },
];

const Index = () => {
  return (
    <SignedInUserOnly>
      <HeadComponent />
      <Tabs
        defaultActiveKey="2"
        items={items}
        size="large"
        style={{ display: "flex" }}
        tabBarStyle={{ padding: "0px 20px" }}
      />
    </SignedInUserOnly>
  );
};

export default Index;
